backend_app:
  deployment_name: backend-deployment
  name: backen-app
  tier: backend
  replicas: 1
  image: 
    name: masterdevopscloud/mern-backend
    tag: latest
  port:
    name: backend-port
    number: 5001
  resources:
    requests:
      cpu: "100m"
      memory: "256Mi"
    limits: 
      cpu: "500m" 
      memory: "1Gi"


frontend_app:
  deployment_name: frontend-deployment 
  name: frontend-app
  tier: frontend
  replicas: 1
  image: 
    name: masterdevopscloud/mern-frontend
    tag: latest
  port:
    name: frontend-port
    number: 80
  resources:
    requests:
      cpu: "100m"
      memory: "128Mi"
    limits: 
      cpu: "500m" 
      memory: "512Mi"


db_app:
  statefulset_name: db-statefulset
  service_name: db-app
  name: db-app
  tier: db
  update_strategy: 
    type: RollingUpdate
  securityContext:
    fsGroup: 999
    fsGroupChangePolicy: OnRootMismatch
  replicas: 1
  image: 
    name: mongo
    tag: latest
  port:
    name: db-app-port
    number: 27017
  resources:
    requests:
      cpu: "200m"
      memory: "256Mi"
    limits: 
      cpu: "1" 
      memory: "1Gi"
  volumeMounts:
    mountPath: "/data/db"
  volumeClaimTemplates:
    name: db-volume
    storage: 1Gi
ingress:
  name: mern-app-ingress
  host: mernapp.rcginfo.xyz
  className: nginx
  path: /
  backend_service: client-app
  backend_port: 80

secret:
  name: db-secret
  type: Opaque
  stringData:
    MONGO_INITDB_ROOT_USERNAME: mongoadmin
    MONGO_INITDB_ROOT_PASSWORD: secret
    MONGO_URI: "mongodb://mongoadmin:secret@db-app:27017/BlogApp?authSource=admin"
  