apiVersion: v1
kind: Service
metadata:
  name: server-app
  labels:
    app: backend-app
    tier: backend
spec:
  type: ClusterIP
  selector:
    app: backend-app
    tier: backend   
  ports:
    - name: http 
      targetPort: backend-port
      port: 5001
      protocol: TCP
