apiVersion: v1
kind: Secret
metadata: 
  name: db-secret
type: Opaque
stringData:
  MONGO_INITDB_ROOT_USERNAME: mongoadmin
  MONGO_INITDB_ROOT_PASSWORD: secret
  MONGO_URI: "mongodb://mongoadmin:secret@db-app:27017/BlogApp?authSource=admin"
  
  