apiVersion: v1
kind: Secret
metadata: 
  name: db-secret
data:
  MONGO_INITDB_ROOT_USERNAME: 'bW9uZ29hZG1pbgo='
  MONGO_INITDB_ROOT_PASSWORD: 'c2VjcmV0Cg=='
  MONGO_URI: 'bW9uZ29kYjovL21vbmdvYWRtaW46c2VjcmV0QGRiLWFwcDoyNzAxNy9CbG9nQXBwP2F1dGhTb3VyY2U9YWRtaW4K'
  
  