apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-app-deployment 
  labels:
    app: frontend-app
    tier: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend-app
      tier: frontend
  template:
    metadata: 
      name: frontend-app
      labels:
        app: frontend-app
        tier: frontend
    spec:
      containers:
        - name: frontend-app
          image: masterdevopscloud/mern-frontend
          ports:
            - name: frontend-port
              containerPort: 80
              protocol: TCP
          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"
            limits:
              cpu: "1"
              memory: "2Gi"

