apiVersion: v1
kind: Service
metadata: 
  name: client-app
  labels:
    app: frontend-app
    tier: frontend
spec:
  selector:
        app: frontend-app
        tier: frontend 
  type: ClusterIP
  ports:
    - name: http
      targetPort: frontend-port
      port: 80
