apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mern-app-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  ingressClassName: nginx
  rules:
    - host: mernapp.rcginfo.xyz
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: client-app
                port: 
                  number: 80
