pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                git branch: 'main', url:'https://github.com/Roberto-1998/jenkins_ci_cd_mern_app.git'
            }
        }

        stage('Install Backend Dependencies') {
            steps {
                dir('mern_blog_app/server') {
                    sh 'npm install || yarn install'
                }
            }
        }

        stage('Run Backend Tests') {
            steps {
                dir('mern_blog_app/server') {
                    sh 'npm test || echo "No backend tests yet"'
                }
            }
        }

        stage('Install Frontend Dependencies') {
            steps {
                dir('mern_blog_app/client') {
                    sh 'npm install || yarn install'
                }
            }
        }
        stage('Run Frontend Tests') {
            steps {
                dir('mern_blog_app/client') {
                    sh 'npm test || echo "No frontend tests yet"'
                }
            }
        }

        stage('Build Frontend App') {
            steps {
                dir('mern_blog_app/client') {
                    sh 'npm run build'
                }
            }
        }

        stage('Archive Build Artifacts') {
            steps {
                archiveArtifacts artifacts: 'mern_blog_app/client/build/**', fingerprint: true
            }
        }
    }
}
